[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "shanghai"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[profile.default.fuzz]
runs = 256
max_test_rejects = 65536

[rpc_endpoints]
bsc = "https://bsc-dataseed1.binance.org"
bsc_testnet = "https://data-seed-prebsc-1-s1.binance.org:8545/"

[etherscan]
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
